[package]
name = "atrd"
version = "0.1.0"
edition = "2024"

[dependencies]
hex-literal = "1.0.0"
md5 = { version = "0.7", features = ["std"] }
sha2 = "0.10.9"
xxhash-rust = { version = "0.8.15", features = ["xxh3", "const_xxh3"] }
